# .github/workflows/generate-feeds.yml

name: Generate All Feeds

on:
  push:
    branches:
      - main
  # প্রতি ৬ ঘণ্টা পর পর স্বয়ংক্রিয়ভাবে চলার জন্য এই অংশটি যোগ করা হয়েছে
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # আপনার দেওয়া কমান্ডটি এখানে রাখা হয়েছে যেন package.json ছাড়া কাজ করে
      - name: Install dependencies
        run: npm install firebase xmlbuilder2

      - name: Generate Sitemap
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: node generate-sitemap.js

      - name: Generate Facebook Feed
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: node generate-facebook-feed.js

      - name: Commit and push feed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-generate sitemap and Facebook feed"
          file_pattern: sitemap.xml facebook_feed.xml
